apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oneapp-auth-service
spec:
  hosts:
  - oneapp-auth-service
  http:
  - route:
    - destination:
        host: oneapp-auth-service
    timeout: 1s